# Use an Alpine based image for a lightweight container
FROM --platform=linux/amd64 node:21-alpine

# Set the working directory in the container
WORKDIR /usr/src/core-app-server

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Bundle app source
COPY . .

# Expose the port the app runs on
EXPOSE 8080

# Define the command to run your app
CMD npm run prod:server