name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::123456789012:role/my-github-actions-role
          aws-region: aws-region-1

      - name: Login to Amazon ECR Public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Build and Push Core Application
        env:
          ECR_URI: public.ecr.aws/b6w6o0v0/russian-losses-core
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_URI:$IMAGE_TAG -f Dockerfile.server .
          docker push $ECR_URI:$IMAGE_TAG

      - name: Build and Push Scraper Application
        env:
          ECR_URI: public.ecr.aws/b6w6o0v0/russian-losses-core
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_URI:$IMAGE_TAG -f Dockerfile.scraper .
          docker push $ECR_URI:$IMAGE_TAG
